name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Jest tests
      id: jest-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Jest tests
        setup-command: npm install jest;npm install
        command: npm test
        timeout: 3
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        JEST-TESTS_RESULTS: "${{steps.jest-tests.outputs.result}}"
      with:
        runners: jest-tests
